# Dependencies
markdown:         kramdown
gems:             ['jekyll-paginate']
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maistho
tagline:          'A Blog about Programming'
description:      'This is my blog mostly about programming. I tend to forget things, and as such I post here mostly for my own benefit.'
url:              http://blog.bylundia.se
repository:           https://github.com/maistho/maistho.github.io

author:
  name:           'Gustav Bylund'
  url:            https://blog.bylundia.se
  github:         https://github.com/Maistho

paginate:         5

# Custom vars

github:
  repo:           https://github.com/maistho/maistho.github.io
