# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Maistho
tagline:          'A Blog about Programming'
description:      'This is my blog mostly about programming. I tend to forget things, and as such I post here mostly for my own benefit. I hope that someday someone reads this and finds a solution to a problem.'
url:              http://blog.bylundia.se

author:
  name:           'Gustav Bylund'
  url:            https://blog.bylundia.se
  github:         https://github.com/Maistho
  cv:             https://bylundia.se/CV

paginate:         5

# Custom vars

github:
  repo:           https://github.com/maistho/maistho.github.io
